version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: chat-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: chatdb
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
