version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: common_chat
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "33066:3306"
    volumes:
      - ./data:/var/lib/mysql

  mongodb:
    image: mongo:7.0
    container_name: chat-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: chatdb
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis
    container_name: chatting_redis
    ports:
      - "6379:6379"
    volumes:
      - /Users/maxxing/Documents/GIT-HUB/COMMON_CHATTING/setting/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  mongo_data: