version: '3'
services:
  redis:
    image: redis
    container_name: chatting_redis
    ports:
      - "6379:6379"
    volumes:
      - /Users/maxxing/Documents/GIT-HUB/COMMON_CHATTING/setting/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf